CREATE TABLE "JOE"."PERSON" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FATHER_NAME" VARCHAR2(100 BYTE), 
	"MOTHER_NAME" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE, 
	"PLACE_OF_BIRTH" VARCHAR2(100 BYTE), 
	"DATE_OF_DEATH" DATE, 
	"PLACE_OF_DEATH" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FAMILY_TREE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FAMILY_TREE" ;

INSERT
INTO
  person
  ( 
    id,
    father_name,
    mother_name,
    name,
    place_of_birth,
    date_of_birth,
    place_of_death,
    date_of_death    
  )
  VALUES
  (
    1,
    'Samuel Thoroman',
    'Cynthiann McDonald Reynolds',
    'William Zenos Thoroman',
    'Ohio',
    TO_DATE('March 4, 1827','Month dd, YYYY'),
    'Jacksonville, Ohio',
    TO_DATE('January 29, 1900','Month dd, YYYY')
  );
