--------------------------------------------------------
--  DDL for Procedure INSERT_OR_UPDATE_BIRTH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INSERT_OR_UPDATE_BIRTH" 
(
  P_ID IN NUMBER 
, PLACE_OF_BIRTH IN VARCHAR2 
, DATE_OF_BIRTH IN DATE 
) AS 
  PLACE_OF_BIRTH_ID NUMBER;
  DUMMY NUMBER;
BEGIN
   -- First, map place
  IF PLACE_OF_BIRTH IS NOT NULL THEN
    BEGIN
      INSERT_PLACE_PROCEDURE(PLACE_OF_BIRTH, PLACE_OF_BIRTH_ID);
      SELECT PERSON_ID INTO DUMMY FROM BIRTH WHERE PERSON_ID=P_ID;
      UPDATE BIRTH SET PLACE_ID=PLACE_OF_BIRTH_ID WHERE PERSON_ID=P_ID;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      INSERT INTO BIRTH (PERSON_ID, PLACE_ID) VALUES (P_ID, PLACE_OF_BIRTH_ID);
    END;
  END IF;
  
  -- Now, insert date
  IF DATE_OF_BIRTH IS NOT NULL THEN
    BEGIN
      SELECT PERSON_ID INTO DUMMY FROM BIRTH WHERE PERSON_ID=P_ID;
      UPDATE BIRTH SET "DATE"=DATE_OF_BIRTH WHERE PERSON_ID=P_ID;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      INSERT INTO BIRTH (PERSON_ID, "DATE") VALUES (P_ID, DATE_OF_BIRTH);
    END;
  END IF;
END INSERT_OR_UPDATE_BIRTH;

/
