--------------------------------------------------------
--  DDL for Procedure INSERT_PLACE_PROCEDURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INSERT_PLACE_PROCEDURE" 
(
  PLACE_NAME IN VARCHAR2 
, PLACE_ID OUT NUMBER 
) AS 
BEGIN
  BEGIN
      SELECT ID INTO PLACE_ID FROM PLACE WHERE PLACE_NAME=PLACE.NAME;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      INSERT INTO PLACE (NAME) VALUES (PLACE_NAME);
      SELECT ID INTO PLACE_ID FROM PLACE WHERE PLACE_NAME=PLACE.NAME;
    END;
END INSERT_PLACE_PROCEDURE;

/
