--------------------------------------------------------
--  Ref Constraints for Table BIRTH
--------------------------------------------------------

  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_ABOUT_FK" FOREIGN KEY ("ABOUT")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_DAY_KNOWN_FK" FOREIGN KEY ("DAY_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_MONTH_KNOWN_FK" FOREIGN KEY ("MONTH_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_PERSON_FK" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_PLACE_FK" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "PLACE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_YEAR_KNOWN_FK" FOREIGN KEY ("YEAR_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
