--------------------------------------------------------
--  Ref Constraints for Table BURIAL
--------------------------------------------------------

  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_ABOUT_FK" FOREIGN KEY ("ABOUT")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_DAY_KNOWN_FK" FOREIGN KEY ("DAY_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_MONTH_KNOWN_FK" FOREIGN KEY ("MONTH_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_PERSON_FK" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_PLACE_FK" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "PLACE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "BURIAL" ADD CONSTRAINT "BURIAL_YEAR_KNOWN_FK" FOREIGN KEY ("YEAR_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
