--------------------------------------------------------
--  Ref Constraints for Table DEATH
--------------------------------------------------------

  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_ABOUT_FK" FOREIGN KEY ("ABOUT")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_DAY_KNOWN_FK" FOREIGN KEY ("DAY_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_MONTH_KNOWN_FK" FOREIGN KEY ("MONTH_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_PERSON_FK" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_PLACE_FK" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "PLACE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_YEAR_KNOWN_FK" FOREIGN KEY ("YEAR_KNOWN")
	  REFERENCES "BOOLEAN" ("ID") ENABLE;
