--------------------------------------------------------
--  DDL for Trigger FATHER_OF_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FATHER_OF_TRIGGER" 
BEFORE INSERT OR UPDATE OF FATHER_ID ON FATHER_OF 
  FOR EACH ROW
DECLARE
  GENDER_ABBR CHAR(1);
  WRONG_GENDER EXCEPTION;
BEGIN
  SELECT GENDER INTO GENDER_ABBR FROM PERSON WHERE PERSON.ID=:new.FATHER_ID;
  
  IF GENDER_ABBR <> 'M' THEN
    RAISE WRONG_GENDER;
  END IF;
END;
/
ALTER TRIGGER "FATHER_OF_TRIGGER" ENABLE;
