--------------------------------------------------------
--  DDL for Trigger MOTHER_OF_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MOTHER_OF_TRIGGER" 
BEFORE INSERT OR UPDATE OF MOTHER_ID ON MOTHER_OF 
  FOR EACH ROW
DECLARE
  GENDER_ABBR CHAR(1);
  WRONG_GENDER EXCEPTION;
BEGIN
  SELECT GENDER INTO GENDER_ABBR FROM PERSON WHERE PERSON.ID=:new.MOTHER_ID;
  
  IF GENDER_ABBR <> 'F' THEN
    RAISE WRONG_GENDER;
  END IF;
END;
/
ALTER TRIGGER "MOTHER_OF_TRIGGER" ENABLE;
