--------------------------------------------------------
--  DDL for Trigger PERSON_VIEW_UPDATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PERSON_VIEW_UPDATE_TRIGGER" 
INSTEAD OF UPDATE ON PERSON_VIEW
DECLARE
  GENDER_ABBR CHAR(1);
  DUMMY NUMBER;
BEGIN
  IF :new.ID IS NOT NULL THEN
  
    -- Update NAME and GENDER, which are required in the tables anyway
    -- (NOT NULL constraints)
    IF :new.NAME IS NOT NULL THEN
      UPDATE PERSON SET NAME=:new.NAME WHERE ID=:new.ID;
    END IF;
    
    IF :new.GENDER IS NOT NULL THEN
      SELECT ABBR INTO GENDER_ABBR FROM GENDER WHERE GENDER.FULL_WORD=:new.GENDER;
      UPDATE PERSON SET GENDER=GENDER_ABBR WHERE ID=:new.ID;
    END IF;
    
    -- Insert / update parents
    IF :new.FATHER_ID IS NOT NULL THEN
       BEGIN
          SELECT FATHER_ID INTO DUMMY FROM FATHER_OF WHERE CHILD_ID=:new.ID;
          UPDATE FATHER_OF SET FATHER_ID=:new.FATHER_ID WHERE CHILD_ID=:new.ID;
       EXCEPTION WHEN NO_DATA_FOUND THEN
          INSERT INTO FATHER_OF (FATHER_ID, CHILD_ID) VALUES (:new.FATHER_ID, :new.ID);
       END;
    END IF;
    
    IF :new.MOTHER_ID IS NOT NULL THEN
       BEGIN
          SELECT MOTHER_ID INTO DUMMY FROM MOTHER_OF WHERE CHILD_ID=:new.ID;
          UPDATE MOTHER_OF SET MOTHER_ID=:new.MOTHER_ID WHERE CHILD_ID=:new.ID;
       EXCEPTION WHEN NO_DATA_FOUND THEN
          INSERT INTO MOTHER_OF (MOTHER_ID, CHILD_ID) VALUES (:new.MOTHER_ID, :new.ID);
       END;
    END IF;
    
  END IF;
END;
/
ALTER TRIGGER "PERSON_VIEW_UPDATE_TRIGGER" ENABLE;
