--------------------------------------------------------
--  DDL for Trigger REGION_OF_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "REGION_OF_TRIGGER" 
BEFORE INSERT OR UPDATE OF PLACE_ID,REGION_ID ON REGION_OF
FOR EACH ROW
DECLARE
  PLACE_LEVEL NUMBER;
  REGION_LEVEL NUMBER;
  REGION_EXCEPTION EXCEPTION;
BEGIN
  SELECT TYPE INTO PLACE_LEVEL FROM PLACE WHERE ID=:new.PLACE_ID;
  SELECT TYPE INTO REGION_LEVEL FROM PLACE WHERE ID=:new.REGION_ID;
  
  IF PLACE_LEVEL < REGION_LEVEL THEN
    RAISE REGION_EXCEPTION;
  END IF;
END;
/
ALTER TRIGGER "REGION_OF_TRIGGER" ENABLE;
