--------------------------------------------------------
--  DDL for Type CUSTOM_DATE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "CUSTOM_DATE" AS OBJECT 
( 
    DATE_OF DATE,
    ABOUT NUMBER,
    YEAR_KNOWN NUMBER,
    MONTH_KNOWN NUMBER,
    DAY_KNOWN NUMBER,
    MEMBER FUNCTION IS_ABOUT RETURN BOOLEAN,
    MEMBER FUNCTION IS_YEAR_KNOWN RETURN BOOLEAN,
    MEMBER FUNCTION IS_MONTH_KNOWN RETURN BOOLEAN,
    MEMBER FUNCTION IS_DAY_KNOWN RETURN BOOLEAN
);
/
CREATE OR REPLACE TYPE BODY "CUSTOM_DATE" AS 
   MEMBER FUNCTION IS_ABOUT RETURN BOOLEAN IS
   BEGIN
      RETURN ABOUT = 1;
   END IS_ABOUT;
   
   MEMBER FUNCTION IS_YEAR_KNOWN RETURN BOOLEAN IS
   BEGIN
      RETURN YEAR_KNOWN = 1;
   END IS_YEAR_KNOWN;
   
   MEMBER FUNCTION IS_MONTH_KNOWN RETURN BOOLEAN IS
   BEGIN
      RETURN MONTH_KNOWN = 1;
   END IS_MONTH_KNOWN;
   
   MEMBER FUNCTION IS_DAY_KNOWN RETURN BOOLEAN IS
   BEGIN
      RETURN DAY_KNOWN = 1;
   END IS_DAY_KNOWN;
END;

/
