--------------------------------------------------------
--  DDL for View CHILDREN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHILDREN_VIEW" ("ID", "NAME", "SPOUSE_ID", "SPOUSE", "CHILD_ID", "CHILD") AS 
  SELECT 
    P.ID,
	  P.NAME,
    SPOUSE.ID AS SPOUSE_ID,
    SPOUSE.NAME AS SPOUSE,
    CHILD.ID AS CHILD_ID,
    CHILD.NAME AS CHILD
FROM 
    PERSON_VIEW CHILD
INNER JOIN 
    PERSON_VIEW P
ON
    CHILD.FATHER_ID = P.ID OR CHILD.MOTHER_ID = P.ID
LEFT OUTER JOIN
    PERSON_VIEW SPOUSE
ON
    (CHILD.FATHER_ID = SPOUSE.ID OR CHILD.MOTHER_ID = SPOUSE.ID) AND
    P.ID <> SPOUSE.ID
ORDER BY
    P.NAME, SPOUSE.NAME;
