--------------------------------------------------------
--  DDL for View DEFAULT_PERSON_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "DEFAULT_PERSON_VIEW" ("ID", "FATHER_ID", "FATHER_NAME", "MOTHER_ID", "MOTHER_NAME", "NAME", "GENDER", "PLACE_OF_BIRTH", "DATE_OF_BIRTH", "PLACE_OF_DEATH", "DATE_OF_DEATH") AS 
  SELECT 
    "ID","FATHER_ID","FATHER_NAME","MOTHER_ID","MOTHER_NAME","NAME","GENDER","PLACE_OF_BIRTH","DATE_OF_BIRTH","PLACE_OF_DEATH","DATE_OF_DEATH"
FROM 
  PERSON_VIEW
WHERE
  ID = (CASE 
          WHEN (SELECT DEFAULT_PERSON FROM SETTINGS) IS NOT NULL
          THEN (SELECT DEFAULT_PERSON FROM SETTINGS)
          ELSE (SELECT MIN(ID) FROM PERSON)
       END);
