--------------------------------------------------------
--  DDL for View PER_DECADE_CLEAN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "PER_DECADE_CLEAN_VIEW" ("BIRTHS", "DEATHS", "DECADE") AS 
  SELECT NVL( BIRTH.COUNT,0 ) BIRTHS,
  NVL( DEATH.COUNT,0 ) DEATHS,
  NVL( BIRTH.DECADE,DEATH.DECADE ) DECADE
FROM
  (
    SELECT COUNT( * ) COUNT,
      ( D.YEAR - AVERAGE - MOD( D.YEAR - AVERAGE,10 ) ) DECADE
    FROM EVENT D, (SELECT AVG(AGE) AVERAGE FROM AGE_VIEW)
    WHERE D.TYPE = 'death'
      AND D.YEAR IS NOT NULL
      AND( D.PERSON_ID NOT IN
      (
        SELECT PERSON_ID FROM EVENT WHERE TYPE = 'birth'
      )
      OR EXISTS
      (
        SELECT * FROM EVENT B WHERE B.TYPE = 'birth' AND B.YEAR IS NULL AND B.PERSON_ID=D.PERSON_ID
      ) )
    GROUP BY( D.YEAR - AVERAGE - MOD( D.YEAR - AVERAGE,10 ) )
  )
  BIRTH
FULL OUTER JOIN
  (
    SELECT COUNT( * ) COUNT,
      ( B.YEAR + AVERAGE - MOD( B.YEAR + AVERAGE ,10 ) ) DECADE
    FROM EVENT B, (SELECT AVG(AGE) AVERAGE FROM AGE_VIEW)
    WHERE B.TYPE = 'birth'
      AND B.YEAR IS NOT NULL
      AND( B.PERSON_ID NOT IN
      (
        SELECT PERSON_ID FROM EVENT WHERE TYPE = 'death'
      )
      OR EXISTS
      (
        SELECT * FROM EVENT D WHERE D.TYPE = 'death' AND D.YEAR IS NULL AND D.PERSON_ID=B.PERSON_ID
      ) )
    GROUP BY( B.YEAR + AVERAGE - MOD( B.YEAR + AVERAGE ,10 ) )
  )
  DEATH
ON BIRTH.DECADE = DEATH.DECADE
ORDER BY DECADE;
