--------------------------------------------------------
--  DDL for View PERSON_VIEW_NULL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "PERSON_VIEW_NULL" ("ID", "FATHER_ID", "FATHER_NAME", "MOTHER_ID", "MOTHER_NAME", "NAME", "GENDER", "PLACE_OF_BIRTH", "DATE_OF_BIRTH", "PLACE_OF_DEATH", "DATE_OF_DEATH") AS 
  SELECT 
    "ID","FATHER_ID","FATHER_NAME","MOTHER_ID","MOTHER_NAME","NAME","GENDER","PLACE_OF_BIRTH","DATE_OF_BIRTH","PLACE_OF_DEATH","DATE_OF_DEATH"
FROM 
    PERSON_VIEW
WHERE
    FATHER_ID IS NULL;
