--------------------------------------------------------
--  DDL for View REGION_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "REGION_VIEW" ("REGION_ID", "PLACE_ID") AS 
  SELECT R1.REGION_ID,R3.PLACE_ID
FROM REGION_OF R1, REGION_OF R2, REGION_OF R3
WHERE R1.PLACE_ID = R2.REGION_ID
  AND R2.PLACE_ID = R3.REGION_ID
UNION 
SELECT R1.REGION_ID,R2.PLACE_ID
FROM REGION_OF R1, REGION_OF R2
WHERE R1.PLACE_ID = R2.REGION_ID
UNION  
SELECT "REGION_ID","PLACE_ID" FROM REGION_OF;
