--------------------------------------------------------
--  DDL for View SETTINGS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SETTINGS_VIEW" ("THEME", "DEFAULT_PERSON", "DEFAULT_PERSON_TYPE", "VIEW_WELCOME_PAGE") AS 
  SELECT 
    THEME,
    DEFAULT_PERSON,
    DEFAULT_PERSON_TYPE.DEFAULT_PERSON_TYPE AS DEFAULT_PERSON_TYPE,
    BOOLEAN.VALUE AS VIEW_WELCOME_PAGE
FROM 
    SETTINGS,
    DEFAULT_PERSON_TYPE,
    BOOLEAN
WHERE
    DEFAULT_PERSON_TYPE.ID = SETTINGS.DEFAULT_PERSON_TYPE
AND BOOLEAN.ID = SETTINGS.VIEW_WELCOME_PAGE;
