--------------------------------------------------------
--  DDL for View SPOUSE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SPOUSE_VIEW" ("ID", "SPOUSE_ID") AS 
  SELECT P.MOTHER_ID ID, SPOUSE.FATHER_ID SPOUSE_ID
FROM MOTHER_OF P, FATHER_OF SPOUSE
WHERE P.CHILD_ID = SPOUSE.CHILD_ID
UNION
SELECT P.FATHER_ID ID, SPOUSE.MOTHER_ID SPOUSE_ID
FROM FATHER_OF P, MOTHER_OF SPOUSE
WHERE P.CHILD_ID = SPOUSE.CHILD_ID
UNION
SELECT M.WIFE ID, M.HUSBAND SPOUSE_ID
FROM MARRIAGE M
UNION
SELECT M.HUSBAND ID, M.WIFE SPOUSE_ID
FROM MARRIAGE M;
