--------------------------------------------------------
--  Constraints for Table BIRTH
--------------------------------------------------------

  ALTER TABLE "BIRTH" MODIFY ("ABOUT" NOT NULL ENABLE);
  ALTER TABLE "BIRTH" MODIFY ("MONTH_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "BIRTH" MODIFY ("DAY_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "BIRTH" MODIFY ("YEAR_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "BIRTH" ADD CONSTRAINT "BIRTH_PK" PRIMARY KEY ("PERSON_ID") ENABLE;
  ALTER TABLE "BIRTH" MODIFY ("PERSON_ID" NOT NULL ENABLE);
