--------------------------------------------------------
--  Constraints for Table DEATH
--------------------------------------------------------

  ALTER TABLE "DEATH" MODIFY ("ABOUT" NOT NULL ENABLE);
  ALTER TABLE "DEATH" MODIFY ("MONTH_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "DEATH" MODIFY ("DAY_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "DEATH" MODIFY ("YEAR_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "DEATH" ADD CONSTRAINT "DEATH_PK" PRIMARY KEY ("PERSON_ID") ENABLE;
  ALTER TABLE "DEATH" MODIFY ("PERSON_ID" NOT NULL ENABLE);
