--------------------------------------------------------
--  Constraints for Table MARRIAGE
--------------------------------------------------------

  ALTER TABLE "MARRIAGE" MODIFY ("ABOUT" NOT NULL ENABLE);
  ALTER TABLE "MARRIAGE" MODIFY ("MONTH_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "MARRIAGE" MODIFY ("DAY_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "MARRIAGE" MODIFY ("YEAR_KNOWN" NOT NULL ENABLE);
  ALTER TABLE "MARRIAGE" ADD CONSTRAINT "MARRIAGE_PK" PRIMARY KEY ("HUSBAND", "WIFE") ENABLE;
  ALTER TABLE "MARRIAGE" MODIFY ("WIFE" NOT NULL ENABLE);
  ALTER TABLE "MARRIAGE" MODIFY ("HUSBAND" NOT NULL ENABLE);
