DELETE FROM PERSON;
DELETE FROM PLACE;

DROP SEQUENCE "PERSON_SEQUENCE";
CREATE SEQUENCE "PERSON_SEQUENCE" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE;

DROP  SEQUENCE "PLACE_SEQUENCE";
CREATE SEQUENCE "PLACE_SEQUENCE" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE;