SELECT 'DROP TABLE ' || TABLE_NAME || ' CASCADE CONSTRAINTS;' FROM USER_TABLES
UNION
SELECT 'DROP VIEW ' || VIEW_NAME || ';' FROM USER_VIEWS
UNION
SELECT 'DROP SEQUENCE ' || SEQUENCE_NAME || ';' FROM USER_SEQUENCES;
