REM INSERTING into JOE.PERSON
SET DEFINE OFF;
Insert into JOE.PERSON (ID,FATHER_ID,MOTHER_ID,NAME,PLACE_OF_BIRTH,DATE_OF_BIRTH,PLACE_OF_DEATH,DATE_OF_DEATH,GENDER) values (1,2,3,'William Zenos Thoroman',1,to_date('04-MAR-27','DD-MON-RR'),3,to_date('29-JAN-00','DD-MON-RR'),'M');
Insert into JOE.PERSON (ID,FATHER_ID,MOTHER_ID,NAME,PLACE_OF_BIRTH,DATE_OF_BIRTH,PLACE_OF_DEATH,DATE_OF_DEATH,GENDER) values (2,null,null,'Samuel Thoroman',2,to_date('23-MAY-95','DD-MON-RR'),1,to_date('12-DEC-81','DD-MON-RR'),'M');
Insert into JOE.PERSON (ID,FATHER_ID,MOTHER_ID,NAME,PLACE_OF_BIRTH,DATE_OF_BIRTH,PLACE_OF_DEATH,DATE_OF_DEATH,GENDER) values (3,null,null,'Cynthiann McDonald Reynolds',null,null,null,null,'F');
