--------------------------------------------------------
--  DDL for View PERSON_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "JOE"."PERSON_VIEW" ("ID", "FATHER_ID", "FATHER", "MOTHER_ID", "MOTHER", "NAME", "GENDER", "PLACE_OF_BIRTH", "DATE_OF_BIRTH", "PLACE_OF_DEATH", "DATE_OF_DEATH") AS 
  SELECT 
    P."ID",
    P.FATHER_ID,
    F."NAME" AS FATHER,
    P.MOTHER_ID,
    M."NAME" AS MOTHER,
    P."NAME",
    GENDERS.FULL_WORD AS GENDER,
    B.NAME AS PLACE_OF_BIRTH,
    P.DATE_OF_BIRTH,
    D.NAME AS PLACE_OF_DEATH,
    P.DATE_OF_DEATH
FROM 
    PERSON P
JOIN
    GENDERS
ON
    P.GENDER = GENDERS.ABBR
LEFT OUTER JOIN 
    PERSON F
ON
    P.FATHER_ID = F."ID"
LEFT OUTER JOIN
    PERSON M
ON
    P.MOTHER_ID = M."ID"
LEFT OUTER JOIN
    PLACE D
ON
    P.PLACE_OF_DEATH = D.ID
LEFT OUTER JOIN
    PLACE B
ON
    P.PLACE_OF_BIRTH = B.ID;
