--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "JOE"."PERSON" ADD CONSTRAINT "PERSON_BIRTH_PLACE_FK" FOREIGN KEY ("PLACE_OF_BIRTH")
	  REFERENCES "JOE"."PLACE" ("ID") ENABLE;
  ALTER TABLE "JOE"."PERSON" ADD CONSTRAINT "PERSON_DEATH_PLACE_FK" FOREIGN KEY ("PLACE_OF_DEATH")
	  REFERENCES "JOE"."PLACE" ("ID") ENABLE;
  ALTER TABLE "JOE"."PERSON" ADD CONSTRAINT "PERSON_FATHER_FK" FOREIGN KEY ("FATHER_ID")
	  REFERENCES "JOE"."PERSON" ("ID") ENABLE;
  ALTER TABLE "JOE"."PERSON" ADD CONSTRAINT "PERSON_GENDER_FK" FOREIGN KEY ("GENDER")
	  REFERENCES "JOE"."GENDERS" ("ABBR") ENABLE;
  ALTER TABLE "JOE"."PERSON" ADD CONSTRAINT "PERSON_MOTHER_FK" FOREIGN KEY ("MOTHER_ID")
	  REFERENCES "JOE"."PERSON" ("ID") ENABLE;
